[build]
  ignore = "/bin/false"
  base = ".markpub"
  publish = "./output"
  command = "pip install --upgrade pip && pip install markpub && markpub build -i .. -o ./output --lunr --commits"

[build.environment]
  PYTHON_VERSION = "3.12"
